version: "3.8"

services:
  recipeapipython:
    build:
      context: .
    ports:
      - 8000:8000
    command: sh -c "python manage.py runservicer 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipeapipython
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=notarealpassword
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=recipeapipython
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notarealpassword
